<%@ Page Title="About" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.vb" Inherits="Site_Simon2.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SWAT_2007</h2>
    <p>J&#39;ai crée cette chaÎne parce que mon frère Shot_to_killYT. Mais amis mon aider comme <span id="channel-title0" class="style-scope ytd-c4-tabbed-header-renderer" style="margin: 0px; padding: 0px; border: 0px; background: transparent; display: inline; color: var(--yt-lightsource-primary-title-color); font-size: 2.4rem; font-weight: 400; line-height: 3rem;">Les 2 Gamers Pros, <span id="channel-title1" class="style-scope ytd-c4-tabbed-header-renderer" style="margin: 0px; padding: 0px; border: 0px; background: transparent; display: inline; color: var(--yt-lightsource-primary-title-color); font-size: 2.4rem; font-weight: 400; line-height: 3rem;">XM Games et <span id="channel-title2" class="style-scope ytd-c4-tabbed-header-renderer" style="margin: 0px; padding: 0px; border: 0px; background: transparent; display: inline; color: var(--yt-lightsource-primary-title-color); font-size: 2.4rem; font-weight: 400; line-height: 3rem;">Cedrik Castonguay. </span></span></span></p>
    <h1 id="channel-title-container1" class="style-scope ytd-c4-tabbed-header-renderer" style="border-style: none; border-color: inherit; border-width: 0px; margin: 0px; padding: 0px; background: rgb(250, 250, 250); max-height: 9rem; overflow: hidden; color: rgb(0, 0, 0); font-family: Roboto, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; font-size: medium;">&nbsp;</h1>
    <h1 id="channel-title-container0" class="style-scope ytd-c4-tabbed-header-renderer" style="border-style: none; border-color: inherit; border-width: 0px; margin: 0px; padding: 0px; background: rgb(250, 250, 250); max-height: 9rem; overflow: hidden; color: rgb(0, 0, 0); font-family: Roboto, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; font-size: medium;">&nbsp;</h1>
    <h1 id="channel-title-container" class="style-scope ytd-c4-tabbed-header-renderer" style="border-style: none; border-color: inherit; border-width: 0px; margin: 0px; padding: 0px; background: rgb(250, 250, 250); max-height: 9rem; overflow: hidden; color: rgb(0, 0, 0); font-family: Roboto, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; font-size: medium;">&nbsp;</h1>
</asp:Content>
